name: Build and Release Image


on:
  pull_request:


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: edc-ui
  IMAGE_NAME_BASE: ${{ github.repository_owner }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout code
      - uses: actions/checkout@v3

      - name: Log in to the Container registry (push-only)
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Store latest commit's author, message and SHA
        run: |
          touch src/assets/.version
          echo "Saving local commit in .version"
          git log -1 > src/assets/.version
          echo "Latest local commit is: "
          git log -1
          echo "github SHA is: "
          echo "${{github.sha}}"
          echo "github SHA of PR is: "
          echo "${{github.event.pull_request.head.sha}}"
          echo ".version is: "
          cat src/assets/.version

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_BASE }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=EDC-UI extended by sovity
            org.opencontainers.image.description=EDC-UI for sovity's extended EDC-Connector.
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,enable={{is_default_branch}}
            type=raw,value=${{ inputs.imageName }},enabled=${{ github.event_name == 'workflow_dispatch' }}

      - name: Build EDC-UI image
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile
          build-args: |
            EDC_UI_CONFIGURATION=production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
